version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  unit-test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/run-tests:
          test-command: ./gradlew SnacksHtml:jacocoTestReport
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/coverage-report/" -exec cp {} ~/test-results/ \;
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - run: mvn test
      - store_artifacts:
          path:  "~/home/circleci/project/SnacksHtml/.circleci/"
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  test-and-build:
    jobs:
      - unit-test