version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  unit-test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run: mvn test
      - store_artifacts:
          path: ~/test-results/junit
      - override:
        - gradle check jacocoTestReport
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  test-and-build:
    jobs:
      - unit-test